adds it assistance page
thereserveforce/www.thereserveforce.com pull request #42
Opened 2020-04-28 22:08 UTC by rbenson09

need to check the format before I add more content. the menu item was also added to the config.yml

2020-05-11 23:11 UTC, felicianotech commented
@rbenson09 How do you want me to go about this review? Would you rather I point out problems with suggestions? Or would you rather I fix the problems?

2020-05-11 23:21 UTC, rbenson09 commented
@felicianotech either way is fine. i don’t mind fixing it myself after your review.

2020-06-30 22:24 UTC, FelicianoTech requested changes
I made some comments.

Also, the three images you're trying to use weren't included in this PR/commit. This is why CircleCI is failing.

2020-06-30 22:24 UTC, felicianotech commented on src/content/all/it-assistance.md
> +{{<figure src="/assets/img/content/install-root-install-certificates.jpg"class="align center small">}}
There needs to be a space after `certificates.jpg"`.

Also, `align center` should be `aligncenter`.

2020-07-20 21:57 UTC, FelicianoTech approved these changes
Looks good to me.

2020-08-03 20:32 UTC, merged